stages:
  - scan
  - build
  - deploy
  - update-dependencies

osv-scanner:
  stage: scan
  image: golang:latest
  script:
    - go install github.com/google/osv-scanner/cmd/osv-scanner@v1
    - osv-scanner -r .

build:
  image: gradle:jdk17
  stage: build
  except:
    - schedules
  artifacts:
    paths:
      - ./build/libs/mlgRush-1.0.0-dev.jar
  variables:
    USERNAME: $NEXUS_USER
    PASSWORD: $NEXUS_PWD
  script:
    - chmod 777 gradlew
    - ./gradlew build

deploy:
  image: justtreme/lftp:4.8.1
  stage: deploy
  only:
    - main
  except:
    - schedules
  dependencies:
    - build
  script:
    - lftp -e "set sftp:auto-confirm yes; mirror -X .* -X .*/ --reverse --verbose ./build/libs /home/simplecloud/templates/MLGRush/plugins; bye" -u $SFTP_USER,$SFTP_PWD sftp://89.163.129.221

renovate:
  image: renovate/renovate
  stage: update-dependencies
  only:
    - schedules
  script:
    - renovate --platform gitlab --token $RENOVATE_TOKEN $CI_PROJECT_PATH
