stages:
  - build
  - deploy
  - update-dependencies

build:
  image: gradle:jdk17
  stage: build
  except:
    - schedules
  artifacts:
    paths:
      - ./build/libs/mlgRush-1.0.0.jar
  variables:
    USERNAME: $NEXUS_USER
    PASSWORD: $NEXUS_PWD
  script:
    - chmod 777 gradlew
    - ./gradlew build

deploy:
  image: justtreme/lftp:4.8.1
  stage: deploy
  only:
    - main
  except:
    - schedules
  dependencies:
    - build
  script:
    - lftp -e "set sftp:auto-confirm yes; mirror -X .* -X .*/ --reverse --verbose ./build/libs /home/laudynetwork/prod/local/templates/MLG-Rush/default/plugins; bye" -u $SFTP_USER,$SFTP_PWD sftp://89.163.129.221

renovate:
  image: renovate/renovate
  stage: update-dependencies
  only:
    - schedules
  script:
    - renovate --platform gitlab --token $RENOVATE_TOKEN $CI_PROJECT_PATH
