name: Java CI/CD

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu
    - name: Build with Gradle
      run: ./gradlew shadowJar
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PWD: ${{ secrets.NEXUS_PWD }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: proxyaddon-latest-all.jar
        path: ./build/libs/proxyaddon-latest-all.jar
