name: Java CI/CD

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu
    - name: Build with Gradle
      run: |
          chmod 777 gradlew
          ./gradlew shadowJar
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PWD: ${{ secrets.NEXUS_PWD }}
